[package]
name = "stroids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.33.3"
winit = "0.26.0"
vk-shader-macros = "0.2.7"
nalgebra = "0.30.1"
obj-rs = "0.7.0"
image = "0.23.14"
